### PR TITLE
Feat/files grouped by day

### PR DESCRIPTION
**Pull request by nbittich**
DL-2878
(sorry I accidentally reformatted the code, if that's a problem I can redo the pr)

### CODE REVIEW

**Comment by madnificent** [comment]
Some basic remarks:

- It may be handy if the formatting could be undone. It makes it hard to review what has effectively changed & I'm weary of version conflicts with [feature/update-configuration-api](https://github.com/lblod/delta-consumer/tree/feature/update-configuration-api) which should receive some attention too (I already hold my heart for doing the exact same reformatting accidentally but I guess merging upstream changes will become near impossible otherwise).
- configuration seems to come from `/cfg` rather than `/config` which is where I think it should come from.  `/config/` can be overridden by the user at runtime and I guess these are configuration parameters?
- The branch is named feat/files where the naming convention is feature/files.  Not a big one but possibly nicer to keep that consistent.

Could you add a motivation as to what you're aiming to achieve and why?  I can guess on the value but your four sentences explaining it will be more insightful :-)

Lastly, to the perceived target change: I think this makes sense.  I did not test-drive the code but looking at the creation of the folder and moving of the file, that looks like a sensible approach.

**Comment by nbittich** [comment]
I'll undo the reformatting, np :D 

For the config change (from config to cfg), it looked to me to be a bug in the repo (I couldn't make it run otherwise), 
 SECRET_KEY, SYNC_LOGIN_ENDPOINT are indeed in cfg, but I may misunderstood it.

**Comment by nbittich** [comment]
Reverted the formatting

**Comment by cecemel** [comment]
@nbittich @madnificent 
Sorry to be such a pain, but currently not sure what the state of master is. So i would suggest to start the changes by branching of the latest tagged version, do them, and apply these to master too.

**Comment by nbittich** [comment]
closed in favor of https://github.com/lblod/delta-consumer/pull/5

**Pull request closed without merging**
